version: "3.8"

services:
  hugo:
    build:
      # To build from github, you need to install docker-compose version=1.27.1 (Does not work with the last versions)
      context: https://github.com/gohugoio/hugo.git
      args:
        - HUGO_BUILD_TAGS=extended

    volumes:
      - ./:/site
    working_dir: /site/src
    ports:
      - ${HUGO_SERVER_PORT}:${HUGO_SERVER_PORT}
    command: server --bind 0.0.0.0 --port ${HUGO_SERVER_PORT}
